name: Main Build
on:
  push:
    paths:
      - 'source/**.py'
      - 'source/**.ps1'
      - '.github/workflows/**.yml'
      - 'scripts/**.ps1'
env:
  VS_PROGRAM: 1
  VS_FILE: 0
  VS_BUGFIX: 0
  VS_EPOCH:
  VS_FULL:
  RELEASE_TITLE: "ArtMap Map Image"
  RELEASE_FILE: "./docs/md/pre-release.md"
  BIN_DEFAULT: "am_mapimage"
  PRERELEASE: True
jobs:
  build_windows:
    name: Build Python Project
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - id: make_am_mapimage
      run: |
        Set-Location scripts
        & '.\build.ps1'
        Get-ChildItem ..\source